In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree

In [2]:
balance_data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data',sep=',',header=None)

In [3]:
balance_data

0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]

In [4]:
len(balance_data)

625

In [5]:
balance_data.shape

(625, 5)

In [6]:
y=balance_data.iloc[:,0]
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0, 2, 1, 0, 2, 2, 2, 1, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 0, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0,
       2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2,
       1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1, 1,
       2, 2, 2, 1, 0, 2, 2, 2, 1, 1, 0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 1,
       0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1,

In [9]:
x=balance_data.iloc[:,1:5]#[:,1:]
x.shape

(625, 4)

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=45)

In [43]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(418, 4) (207, 4) (418,) (207,)


In [11]:
from sklearn.tree import DecisionTreeClassifier
dt_gini=DecisionTreeClassifier(criterion='gini',random_state=100)
dt_gini.fit(x_train,y_train)

DecisionTreeClassifier(random_state=100)

In [12]:
pred=dt_gini.predict(x_test)
pred

array([2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1,
       0, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 0, 2, 1, 2, 1, 2,
       2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 2,
       2, 2, 2, 1, 1, 1, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 1, 0, 2,
       1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 0, 1, 2,
       2, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 1, 1,
       2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 0, 2, 0, 1, 1, 1, 1,
       2, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 0, 2, 2, 1, 1, 2, 1, 1, 2,
       2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 0, 1, 2, 0, 1, 1, 1, 2, 2, 2, 1, 2,
       2, 2, 1, 1, 1, 2, 1, 1, 2])

In [13]:
accuracy_score(y_test,pred)

0.7729468599033816

In [15]:
dt_gini.predict([[4,4,3,3]])

array([1])

In [16]:
dt_en=DecisionTreeClassifier(criterion='entropy',random_state=100)
dt_en.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=100)

In [18]:
pred=dt_en.predict(x_test)
pred

array([2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 1, 1, 1, 0, 2, 1,
       0, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 0, 0, 2, 1, 2, 1, 2,
       2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2,
       2, 2, 2, 1, 2, 1, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 1, 0, 2,
       1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 0, 1, 2,
       2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 1, 1,
       2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       2, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2,
       2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 0, 1, 2, 0, 1, 1, 1, 2, 2, 2, 1, 2,
       2, 2, 1, 1, 1, 2, 1, 1, 2])

In [19]:
accuracy_score(y_test,pred)

0.7777777777777778

In [20]:
def dectree(cr,rs):
    m=DecisionTreeClassifier(criterion=cr,random_state=rs)
    m.fit(x_train,y_train)
    pred=m.predict(x_test)
    print(accuracy_score(y_test,pred))

In [24]:
dectree('gini',50)

0.7922705314009661


In [29]:
dectree('entropy',32)

0.7777777777777778


In [35]:
from sklearn.model_selection import cross_val_score
gnbscores=cross_val_score(dt_gini,x,y,cv=8)
print(gnbscores)
print(gnbscores.mean(),gnbscores.std())

[0.49367089 0.65384615 0.67948718 0.78205128 0.73076923 0.74358974
 0.79487179 0.55128205]
0.6786960402466733 0.10135870515844712


In [37]:
dt_gini.predict([[4,4,3,3]])

array([1])

In [38]:
import joblib
joblib.dump(dt_gini,'dtginimodel.obj')

['dtginimodel.obj']

In [39]:
p=joblib.load('dtginimodel.obj')

In [41]:
p.predict([[4,4,2,5]])

array([1])

In [42]:
t=np.array([1,1,2,5])
t=t.reshape(1,-1)
p.predict(t)

array([2])